### DISCUSSION TITLE
Traefik extras (tls-opts)

### DISCUSSION THREAD

**Discussion by Deadfire-** [tiredofit/docker-traefik#6] [Ideas]
Hello!
I am a fan of your fantastic docker repos files you create, as it has helped me many times professionally and personally. If I could I would like to offer suggestions on default middlewares that this docker image could use. the first would be the following:

../rules/tls-opts.yaml
```
tls:
  options:
    tls-opts:
      minVersion: VersionTLS12
      cipherSuites:
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
        - TLS_AES_128_GCM_SHA256
        - TLS_AES_256_GCM_SHA384
        - TLS_CHACHA20_POLY1305_SHA256
        - TLS_FALLBACK_SCSV # Client is doing version fallback. See RFC 7507
      curvePreferences:
        - CurveP521
        - CurveP384
      sniStrict: true
```
