### ISSUE TITLE
Issue with LetsEncrypt when deactivated

### ISSUE THREAD

**Issue by svzi** [tiredofit/docker-traefik#3]
Hi there!

I'm trying to get traefik running without LetsEncrypt and authentication, just to get it started before I take care of the next issues with certificates. 

This is my `docker-compose.yml`:
```
version: '3.7'
services:
 
  traefik-app:
    image: tiredofit/traefik
    container_name: traefik-app
    environment:
    - ZABBIX_HOSTNAME=traefik-app
    - DOCKERDIR=/volume1/docker
    - DASHBOARD_HOSTNAME=traefik.example.com
    - DEBUG_MODE=true
    - ENABLE_LETSENCRYPT=FALSE
    - ENABLE_DASHBOARD_AUTHENTICATION=FALSE
    ports:
    - 80:80
    - 443:443
    expose:
    - 8080
    labels: 
    - traefik.enable=true
    - traefik.frontend.rule=Host:traefik.example.com
    - traefik.port=8080
    - traefik.protocol=http
    - traefik.docker.network=proxy
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - /volume1/docker/traefik/config:/traefik/config
    - /volume1/docker/traefik/logs:/traefik/logs
    - /volume1/docker/traefik/certs:/traefik/certs
    networks:
    - proxy
    - services
    restart: always

networks:
  proxy:
    external: true
  services:
    external: true
```

When I inspect the logs I see this:
```
traefik-app    | 2021-02-20T23:49:42.084193104Z [INFO] /etc/services.available/10-traefik/run ** [traefik] Starting traefik 2.3.6
traefik-app    | 2021-02-20T23:49:42.084302143Z + exec traefik --configfile /traefik/config/config.yml
traefik-app    | 2021-02-20T23:49:42.114724297Z time="2021-02-20T23:49:42Z" level=info msg="Configuration loaded from file: /traefik/config/config.yml"
traefik-app    | 2021-02-20T23:49:42.406691316Z time="2021-02-20T23:49:42Z" level=error msg="the router dashboard@file uses a non-existent resolver: letsencrypt"
traefik-app    | 2021-02-20T23:49:42.565649780Z time="2021-02-20T23:49:42Z" level=error msg="the router dashboard@file uses a non-existent resolver: letsencrypt"
traefik-app    | 2021-02-20T23:49:43.262674099Z time="2021-02-20T23:49:43Z" level=error msg="the router dashboard@file uses a non-existent resolver: letsencrypt"
```

I had a look at the  `config/custom/dashboard.yml` and it looks this way:
```
http:
  routers:
    dashboard:
      entryPoints:
        - websecure
      service: api@internal
      rule: Host(`traefik.zeemo.app`)
      tls:
        certresolver: letsencrypt
```
That `certresolver` should not be set right now, in my opinion. Is there anything I can do to get it running without LetsEncrypt first?

Best,
Sven
